In [192]:
import pandas as pd
import numpy as np
import random

In [205]:
netflix_entertainment = pd.read_csv('https://raw.githubusercontent.com/datacamp/community-groupby/refs/heads/master/data/chasewillden-netflix-shows/data/netflix.csv')

netflix_entertainment

,title,rating,ratinglevel,ratingdescription,release_year,user_rating_score,user_rating_size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80
...,...,...,...,...,...,...,...
995,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
999,Growing Up Wild,G,NaN,35,2016,80.0,80

## Data Preprocessing And Preparation

In [206]:
netflix_entertainment.head()

,title,rating,ratinglevel,ratingdescription,release_year,user_rating_score,user_rating_size
0,White Chicks,PG-13,"crude and sexual humor, language and some drug...",80,2004,82.0,80
1,Lucky Number Slevin,R,"strong violence, sexual content and adult lang...",100,2006,NaN,82
2,Grey's Anatomy,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2016,98.0,80
3,Prison Break,TV-14,Parents strongly cautioned. May be unsuitable ...,90,2008,98.0,80
4,How I Met Your Mother,TV-PG,Parental guidance suggested. May not be suitab...,70,2014,94.0,80

In [207]:
netflix_entertainment.tail()

,title,rating,ratinglevel,ratingdescription,release_year,user_rating_score,user_rating_size
995,The BFG,PG,"for action/peril, some scary moments and brief...",60,2016,97.0,80
996,The Secret Life of Pets,PG,for action and some rude humor,60,2016,NaN,81
997,Precious Puppies,TV-G,Suitable for all ages.,35,2003,NaN,82
998,Beary Tales,TV-G,Suitable for all ages.,35,2013,NaN,82
999,Growing Up Wild,G,NaN,35,2016,80.0,80

In [208]:
netflix_entertainment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              1000 non-null   object
 1   rating             1000 non-null   object
 2   ratinglevel        941 non-null    object
 3   ratingdescription  1000 non-null   int64
 4   release_year       1000 non-null   int64
 5   user_rating_score  605 non-null    float64
 6   user_rating_size   1000 non-null   int64
dtypes: float64(1), int64(3), object(3)
memory usage: 54.8+ KB

In [209]:
# Keeping titles, rating, rating level, and release year
netflix_entertainment = netflix_entertainment.drop(columns=['ratinglevel', 'ratingdescription', 'user_rating_score', 'user_rating_size'])

In [210]:
# Sort the movies by year
netflix_entertainment = netflix_entertainment.sort_values(by='release_year')

netflix_entertainment

                              title    rating  release_year
761                        Fantasia         G          1940
907                        Fantasia         G          1940
861                        Fantasia         G          1940
933  The Smurfs and the Magic Flute         G          1976
876  The Smurfs and the Magic Flute         G          1976
..                              ...       ...           ...
77               Marvel's Iron Fist     TV-MA          2017
631                        Dinotrux  TV-Y7-FV          2017
630              Dawn of the Croods     TV-Y7          2017
991              Dawn of the Croods     TV-Y7          2017
36               Santa Clarita Diet     TV-MA          2017

[1000 rows x 3 columns]

In [211]:
# Getting rid of duplicate values
netflix_entertainment = netflix_entertainment.drop_duplicates(subset=['title'])

netflix_entertainment

                                   title    rating  release_year
761                             Fantasia         G          1940
933       The Smurfs and the Magic Flute         G          1976
301                               Grease        PG          1978
872                     The Last Unicorn         G          1982
970                                Annie        PG          1982
..                                   ...       ...           ...
348  Felipe Neto: My Life Makes No Sense     TV-MA          2017
729            Dragons: Race to the Edge  TV-Y7-FV          2017
394                         Ingobernable     TV-MA          2017
693       Home: Adventures with Tip & Oh     TV-Y7          2017
630                   Dawn of the Croods     TV-Y7          2017

[496 rows x 3 columns]

In [212]:
# How many unique values in each column?
netflix_entertainment.nunique()

title           496
rating           13
release_year     35
dtype: int64

In [213]:
# All Netflix movie and TV show ratings
netflix_entertainment['rating'].unique()

array(['G', 'PG', 'TV-Y7', 'TV-Y', 'TV-Y7-FV', 'TV-G', 'PG-13', 'R',
       'TV-14', 'TV-PG', 'TV-MA', 'NR', 'UR'], dtype=object)

In [ ]:
# Changing UR to Unrated
netflix_entertainment['rating'] = netflix_entertainment['rating'].replace('UR', 'Unrated')

In [203]:
# Determining the range of release years in file
print(netflix_entertainment['release_year'].min(),
      netflix_entertainment['release_year'].max())

1940 2017

In [215]:
# Creating an array/list of all possible release years
release_years = np.arange(1940, 2018).tolist()

release_years

[1940,
 1941,
 1942,
 1943,
 1944,
 1945,
 1946,
 1947,
 1948,
 1949,
 1950,
 1951,
 1952,
 1953,
 1954,
 1955,
 1956,
 1957,
 1958,
 1959,
 1960,
 1961,
 1962,
 1963,
 1964,
 1965,
 1966,
 1967,
 1968,
 1969,
 1970,
 1971,
 1972,
 1973,
 1974,
 1975,
 1976,
 1977,
 1978,
 1979,
 1980,
 1981,
 1982,
 1983,
 1984,
 1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017]

## Recommend a Movie/TV Show
Recommends a movie or TV Show whenever the user runs this.

In [217]:
# Recommended TV Show/Movie
def recommended_show_movie():

  recommended = netflix_entertainment.sample()

  return recommended

recommended_show_movie()

                    title    rating  release_year
532  All Hail King Julien  TV-Y7-FV          2016

## Netflix Movie and TV Show Recommender
Recommends a list of movies or TV shows depending on the rating and release years chosen.

In [218]:
# List of accepted search answers
movie_answers = ['movie', 'movies']
tv_answers = ['tv show', 'tv', 'tv shows', 'television', 'television show', 'television shows']

movie_ratings = ['g', 'pg', 'pg-13', 'r', 'unrated']
tv_ratings = ['tv-y7', 'tv-y', 'tv-y7-fv', 'tv-g','tv-14', 'tv-pg', 'tv-ma']

In [219]:
# Year Range Search Function
def year_range(new_df, format_prompt):

  while True:

    start_year = input(f"Finally, pick a range of release years you would like the {format_prompt} to be from. Write 'any' if you have no preference. Release year start date (1940 to 2017): ").lower().strip()

    if start_year == 'any':
      return new_df

    try:

      start_year = int(start_year)

      if not (1940 <= start_year <= 2017):
        print("Please enter a year between 1940 and 2017.")
        continue

      end_year = input(f"{format_prompt.capitalize()} year range end date (1940 to 2017): ").lower().strip()

      end_year = int(end_year)

      if not (1940 <= end_year <= 2017):
        print("Please enter a year between 1940 and 2017.")
        continue

      if end_year < start_year:
        print("End year must be greater than or equal to start year.")
        continue

      return new_df[new_df["release_year"].between(start_year, end_year)]

    except ValueError:
      print("Please enter a valid year.")

# Movie/TV Show Rating Search Function
def rating(initial_df, media_format):

  if media_format == 'movie':
    allowed_ratings = movie_ratings
    options = 'G, PG, PG-13, R, or Unrated'
    format_prompt = 'movie'

  else:
    allowed_ratings = tv_ratings
    options = 'TV-Y7, TV-Y, TV-Y7-FV, TV-G, TV-14, TV-PG, TV-MA'
    format_prompt = 'TV show'

  print(f"\nNow, pick the rating the {format_prompt} should have.")

  rating_search = input(f"Please pick one of the following ({options}) or write 'any' if you have no preference: ").lower().strip()

  if rating_search == 'any':
    new_df = initial_df[initial_df["rating"].str.lower().isin(allowed_ratings)]
    return year_range(new_df, media_format)

  elif rating_search in allowed_ratings:
    new_df = initial_df[initial_df["rating"].str.lower() == rating_search]
    return year_range(new_df, media_format)

  else:
    print(f"Invalid selection. Please select from {options} or 'any'.")
    return rating(initial_df, media_format)

# Main Search Function
def search_function():

  print("Welcome to the Netflix Movie and TV Show Recommender, which has movies and TV shows from 1940 to 2017!")

  search = input("Would you like to watch a movie or a TV show? ").lower().strip()

  if search in movie_answers:
    format_type = 'movie'
    return rating(netflix_entertainment, format_type)

  elif search in tv_answers:
    format_type = 'tv'
    return rating(netflix_entertainment, format_type)

  else:
    print("Please pick one: movies or TV shows.")
    return search_function()

search_function()

Welcome to the Netflix Movie and TV Show Recommender, which has movies and TV shows from 1940 to 2017!
Would you like to watch a movie or a TV show?        tv ShOw

Now, pick the rating the TV show should have.
Please pick one of the following (TV-Y7, TV-Y, TV-Y7-FV, TV-G, TV-14, TV-PG, TV-MA) or write 'any' if you have no preference:           tv-y7
Finally, pick a range of release years you would like the tv to be from. Write 'any' if you have no preference. Release year start date (1940 to 2017): any

                                         title rating  release_year
519          The Super Mario Bros. Super Show!  TV-Y7          1989
799                      The Real Ghostbusters  TV-Y7          1990
884                                 Animaniacs  TV-Y7          1997
568                                 Goosebumps  TV-Y7          1998
514                                 The Batman  TV-Y7          2007
509                                 Dino Squad  TV-Y7          2008
562                     Beyblade: Metal Fusion  TV-Y7          2009
797                                    Hatched  TV-Y7          2013
538        Lego DC Comics: Batman Be-Leaguered  TV-Y7          2014
574         Pac-Man and the Ghostly Adventures  TV-Y7          2014
576              Power Rangers Super Megaforce  TV-Y7          2014
540                  Power Rangers Dino Charge  TV-Y7          2015
790               The Adventures of Figaro Pho  TV-Y7          2015
596                                   The Deep  TV-Y7          2015
620                                   Lab Rats  TV-Y7          2016
586           Transformers: Robots in Disguise  TV-Y7          2016
597                         Skylanders Academy  TV-Y7          2016
524                  Transformers: Rescue Bots  TV-Y7          2016
848  LEGO Jurassic World: The Indominus Escape  TV-Y7          2016
595            Power Rangers Dino Super Charge  TV-Y7          2016
841           The Mr. Peabody and Sherman Show  TV-Y7          2017
693             Home: Adventures with Tip & Oh  TV-Y7          2017
630                         Dawn of the Croods  TV-Y7          2017